### ISSUE TITLE
withpinbox导出的html收藏夹无法导入到爱收藏

### ISSUE THREAD

**Issue by gotoorder** [zhaopeiym/LoveCollection#11]
之前保存在withpinbox，但是达到免费的上限了，遂转移阵地。通过withpinbox导出的html，在爱收藏导入不了，一直正在导入中。

**Comment by zhaopeiym** [comment]
现暂时只支持 从浏览器导出的html

**Comment by gotoorder** [comment]
我把书签导入Chrome，再重新从Chrome导出，然后导入爱收藏也不行

**Comment by zhaopeiym** [comment]
我测试了下，可以正常导入。只是速度稍微有点慢。
