### ISSUE TITLE
360极速浏览器问题反馈

### ISSUE THREAD

**Issue by thelongmarch** [zhaopeiym/LoveCollection#6]
1.右击选择自定义分类没有弹框
2.添加到默认分类也没添加成功

**Comment by zhaopeiym** [comment]
1、你是在 https://ext.chrome.360.cn/webstore/search/%E7%88%B1%E6%94%B6%E8%97%8F 安装的插件吗？
2、你是哪个地址测试的？或者，你重新打开下浏览器或刷新再试试呢？

**Comment by thelongmarch** [comment]
问下现在是哪个版本的，http://7xkcgg.com1.z0.glb.clouddn.com/1111.png
一点几的可以用，2点几不可以用。
之后的操作都是用1点几的版本。
其次我想问下，收藏的网址会被其他网址限制么，比如这个网址：https://hugangqiang.com/，
然后我测试了百度首页不可以收藏，再其次搜索的列表也不可以，只有点到具体的某个网址才可以。
方便的加个qq一起学习，2454424641

**Comment by zhaopeiym** [comment]
一般没有限制，只有可能样本被干扰。

已加好友。
