### ISSUE TITLE
请披露关键细节--关于Redis缓存中间件的配置""

### ISSUE THREAD

**Issue by DUWENINK** [zhaopeiym/LoveCollection#9]
我在使用LoveCollection过程中,发现了您使用了`Redis`缓存中间件,这是极好的!
但是我同时也有一些困惑!
当我执行注册方法`Register`的时候
`[HttpPost]
        public async Task<RequestMessage> Register(string mail, string passwod)
        {
            var requestMessage = new RequestMessage() { IsSuccess = true };
            var user = await _collectionDBCotext.Users
                .Where(t => t.Mail == mail)
                .Select(t => new { t.Id, t.Passwod })
                .FirstOrDefaultAsync();

            if (user == null || user.Passwod != passwod)//注册 或 修改密码
            {
                requestMessage.IsSuccess = false;

                RedisHelper reids = new RedisHelper(3);
               
                var key = mail;
                var number = await reids.GetStringIncrAsync(key);
                if (number >= 3)
                {
                    requestMessage.Message = "请勿频繁注册，请查看垃圾邮件或换一个邮箱注册！";
                    return requestMessage;
                }
                //30分钟内有效(标记邮件激活30分钟内有效)
                await reids.SetStringIncrAsync(key, TimeSpan.FromMinutes(30));

                if (user == null)
                    requestMessage.Message = "第一次登录，验证链接已发邮箱。";
                else
                    requestMessage.Message = "您的密码有变更，验证链接已发邮箱。";

                var data = JsonConvert.SerializeObject(new User() { Mail = mail, Passwod = passwod });
                var DESString = HttpUtility.UrlEncode(EncryptDecryptExtension.DES3Encrypt(data, DESKey));
                EmailHelper email = new EmailHelper();
                email.MailToArray = new string[] { mail };
                var checkUrl = Request.Scheme + "://" + Request.Host.Value + "/Home/CheckLogin?desstring=" + DESString;
                email.MailSubject = "欢迎您注册 爱收藏";
                email.MailBody = EmailHelper.TempBody(mail, "请复制打开链接(或者右键'在新标签页中打开')，完成验证。", "<a style='word-wrap: break-word;word-break: break-all;' href='" + checkUrl + "'>" + checkUrl + "</a>");
                email.Send(t =>
                {
                    //string aa = "成功";
                }, t =>
                {
                    //string aa = "失败";
                });
            }
            else
            {
                SaveCookie(new Core.Entities.User() { Id = user.Id, Mail = mail });
            }
            return requestMessage;
        }`

`RedisHelper reids = new RedisHelper(3);`这句方法并没有按照预期执行,我认为这个RedisHelper 类中的构造参数3表示的是本地的redis db3数据库,但是我本地redis是开启的(如图"")
![image](https://user-images.githubusercontent.com/16337239/60242215-b8fd8300-98e7-11e9-8e43-e6b0cc9aa6f5.png)
当我尝试使用这个方法的时候,在`Chrome Console`中报错

`An unhandled exception occurred while processing the request.
Exception: 没有配置redis连接`

**Comment by zhaopeiym** [comment]
你是想把这个应用自己部署一套吗？

**Comment by zhaopeiym** [comment]
你需要在配置文件appsettings.json。ConnectionStrings 的 RedisConnection 下面配置Redis连接。
![image](https://user-images.githubusercontent.com/5820324/60242818-4392b200-98e9-11e9-8295-36dbbe15cd29.png)


#### 然后想问下你的这个redis控制面板是什么软件？

**Comment by DUWENINK** [comment]
> 你是想把这个应用自己部署一套吗？

您好,是的!请问可以支持私有化部署吗

**Comment by zhaopeiym** [comment]
关于RedisHelper的具体实现可以参考：
https://github.com/zhaopeiym/Talk/blob/Dev/Talk.Redis/RedisHelper.cs

**Comment by DUWENINK** [comment]
> #### 然后想问下你的这个redis控制面板是什么软件？

控制面板软件名称为 '[AnotherRedisDesktopManager](https://github.com/qishibo/AnotherRedisDesktopManager)'
